language: objective-c
osx_image: xcode8.3.3
branches:
  only:
    - master

env:
  global:
  - LANG=en_US.UTF-8

before_install:
  - gem update cocoapods
before_script:
  - export LANG=en_US.UTF-8
script:
  - pod update
  - xcodebuild -workspace YapImageManagerExample.xcworkspace -scheme YapImageManagerExample -destination 'OS=10.3.1,name=iPhone 7 Plus' -configuration Debug build | xcpretty;

